[project]
name = 'Automated-Market-Maker'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fee-distribution]
path = 'contracts/fee-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.pool-factory]
path = 'contracts/pool-factory.clar'
clarity_version = 2
epoch = 2.5

[contracts.router]
path = 'contracts/router.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
